---
title: "hao_xu"
author: "Hao Xu"
format: html
---

```{r}
library(here) 
library(readr)  
library(dplyr)
library(ggplot2)
library(tidyr)
library(knitr)  
here::i_am("grades.Rproj")
```
# 1 Personalisation and data set import
## Question1
```{r}
courses <- read_csv(here("data", "courses.csv"))
```
## Question 2
```{r}
courses |>
  arrange(course) |>
  rename(
    "course name" = course,
    "identifier" = course_id,
    "module" = module,
    "number of exams" = nb_grades  
  ) |>
  kable()
```

## Question3
```{r}
students <- read_csv(
  here("data", "students.csv"),
  col_types = cols(
    id = col_integer(),
    group = col_factor(),
    birth_date = col_date(),
    sex = col_factor()
  )
)
```

## Question4
```{r}
grades <- read_delim(
  here("data", "grades.csv"),
  delim = ":",      
  na = "_",         
  col_types = cols( 
    id = col_integer(),
    course_id = col_integer(),
    grade = col_double()
  )
)
```

# 2 Student population analysis
## Question5
```{r}
ggplot(students, aes(x = group)) +
  geom_bar()
```
## Question6
```{r}
ggplot(students, aes(x = group, fill = sex)) +
  geom_bar(position = "fill")
```
## Question7
```{r}
library(lubridate)
students <- students |>
  mutate(
    raw_age = time_length(today() - birth_date, unit = "year"),
    age = raw_age
  )
```

```{r}
ggplot(students, aes(x = age)) +
  geom_density(bw = "sj", fill = "skyblue", alpha = 0.5) +
  geom_rug(alpha = 0.5) 
```
## Question8
```{r}
students |>
  group_by(group) |>
  summarise(
    median_age = as.integer(round(median(age)))
  ) |>
  kable(
    col.names = c("Group", "Median Age"),
  )
```
## Question9
```{r}
students |>
  mutate(age = as.integer(age)) |>
  group_by(group) |>
  slice_max(age, n = 1) |>
  ungroup() |>
  select(id, sex, age) |>
  arrange(desc(age)) |>
  slice_tail(n = 5) |>
  knitr::kable()
```

# 3 Simple grade analysis
## Question10
The data set contains `r sum(!is.na(grades$grade))` grades.
## Question11
```{r}
grades |>
  inner_join(students, by = "id") |>
  inner_join(courses, by = "course_id") |>
  filter(course == "Electrical Engineering and Telegraphy") |>
  group_by(group) |>
  summarise(avg_grade = mean(grade, na.rm = TRUE)) |>
  ggplot(aes(x = group, y = avg_grade)) +
  geom_col(fill = "steelblue") 
```
## Question12
```{r}
grades |>
  inner_join(courses, by = "course_id") |>
  ggplot(aes(x = grade, fill = as.factor(module))) +
  geom_density(alpha = 0.5, na.rm = TRUE)
```
# 4 Attendance analysis

## Question13
```{r}
grades_per_student <- students |>
  inner_join(grades, by = "id") |>
  group_by(id, group, sex) |>
  summarise(nb_grades = n(), .groups = "drop")
```
```{r}
grades_per_student |>
  slice_head(n = 5) |>
  knitr::kable()
```
```{r}
grades_per_student |>
  summarise(
    min = min(nb_grades),
    max = max(nb_grades),
    average = mean(nb_grades),
    median = median(nb_grades)
  ) |>
  knitr::kable(caption = "Summary statistics of grades per student")
```

## Questiuon14
```{r}
ggplot(grades_per_student, aes(x = nb_grades, fill = sex)) +
  geom_density(alpha = 0.5) 
```
## Question15
```{r}
crypto_grades <- grades |>
  inner_join(courses, by = "course_id") |>
  filter(course == "Cryptography and Codebreaking") |>
  inner_join(students, by = "id") |>
  group_by(id, group, sex) |>
  summarise(nb_grades = n(), .groups = "drop")
crypto_grades |>
  slice_head(n = 5) |>
  knitr::kable(caption = "Grades per student in Cryptography")
```

